# Generated by Django 3.2.7 on 2021-10-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_admin_0002_alter_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
