# Generated by Django 3.2.7 on 2021-10-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
        ('mainapp', '0002_productcategory_is_active'),
    ]

    operations = [
    ]
